[build]
  command = "npm install --prefix netlify/functions && npm run build"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  DATABASE_URL = "postgresql://neondb_owner:npg_V8BUntTpyxH6@ep-solitary-star-aeq7oiu0-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"